VIH-9901---new-notify-template-for-lip-3rd-email-48-hour-reminder
hmcts/vh-scheduler-jobs pull request #155
Opened 2023-10-16 08:48 UTC by marcogagliardi

[VIH-9901](https://tools.hmcts.net/jira/browse/VIH-9901)

2023-10-16 14:09 UTC, shaed-parkar reviewed
Few things to address to make it easier to maintain

2023-10-18 06:30 UTC, marcogagliardi commented on SchedulerJobs/SchedulerJobs.Common/Configuration/FeatureToggles.cs
> +        bool UsePostMay2023Template();
done

2023-10-18 06:34 UTC, marcogagliardi commented on SchedulerJobs/SchedulerJobs.Services.UnitTests/AddNotificationRequestMapperTest.cs
> +        ParticipantResponse participant1 = new ParticipantResponse();
done

2023-10-18 06:39 UTC, marcogagliardi commented on SchedulerJobs/SchedulerJobs.Services.UnitTests/AddNotificationRequestMapperTest.cs
> +        hearingDetails.Cases = new List<CaseResponse>();
done

2023-10-18 07:21 UTC, marcogagliardi commented on SchedulerJobs/SchedulerJobs.Services.UnitTests/AddNotificationRequestMapperTest.cs
> +        var participantId = Guid.NewGuid();
refactored

2023-10-18 07:25 UTC, marcogagliardi commented on SchedulerJobs/SchedulerJobs.Services/Mappers/AddNotificationRequestMapper.cs
> +        private static Dictionary<string, string> InitCommonParameters(HearingDetailsResponse hearing, bool featureTogglePost2023 = false)
I don't think you understood this. the toggle is used to decide to add parameters

2023-10-18 07:33 UTC, marcogagliardi commented on SchedulerJobs/SchedulerJobs.Services/Mappers/AddNotificationRequestMapper.cs
> +                    if (featureTogglePost2023)
done

2023-10-18 09:11 UTC, shaed-parkar requested changes

2023-10-18 09:58 UTC, marcogagliardi commented on SchedulerJobs/SchedulerJobs.Services/Mappers/AddNotificationRequestMapper.cs
> +        private static Dictionary<string, string> InitCommonParameters(HearingDetailsResponse hearing, bool featureTogglePost2023 = false)
I don't undesratnd

2023-10-18 09:58 UTC, marcogagliardi commented on SchedulerJobs/SchedulerJobs/local.settings.json
> +  "IsEncrypted": false,
removed

2023-10-19 08:49 UTC, shaed-parkar approved these changes

2023-10-27 09:57 UTC, marcogagliardi commented
/azp run

2023-11-01 08:37 UTC, marcogagliardi commented
/azp run

2023-11-06 15:26 UTC, marcogagliardi commented
/azp run

2023-11-08 12:08 UTC, shaed-parkar approved these changes
The new notification api endpoints are available if you decide to swap over to it

2023-11-08 13:28 UTC, komaldabhi1509 approved these changes

2023-11-08 15:32 UTC, merged